{
 "title": "Istio WASM Extension Dashboard",
 "time": { "from": "2020-10-22T23:11:45.783Z", "to": "2020-10-23T00:04:19.481Z" },
 "panels": [
  {
   "title": "envoy_wasm_active",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "avg(envoy_wasm_vm_null_active)" },
    { "expr": "avg(envoy_wasm_vm_v8_active)" }
   ]
  },
  {
   "title": "envoy_wasm_cloned",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "avg(envoy_wasm_vm_null_cloned)" },
    { "expr": "avg(envoy_wasm_vm_v8_cloned)" },
    {}
   ]
  },
  {
   "title": "envoy_wasm_remote_load_fetch",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(envoy_wasm_remote_load_fetch_failures)",
     "legendFormat": "envoy_wasm_remote_load_fetch_failures"
    },
    {
     "expr": "avg(envoy_wasm_remote_load_fetch_successes)",
     "legendFormat": "envoy_wasm_remote_load_fetch_successes"
    }
   ]
  },
  {
   "title": "envoy_wasm_created",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(envoy_wasm_vm_null_created)"
    },
    { "expr": "avg(envoy_wasm_vm_v8_created)" }
   ]
  },
  {
   "title": "envoy_wasm_remote_load_cache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(envoy_wasm_remote_load_cache_entries)",
     "legendFormat": "envoy_wasm_remote_load_cache_entries"
    },
    {
     "expr": "avg(envoy_wasm_remote_load_cache_hits)",
     "legendFormat": "envoy_wasm_remote_load_cache_hits"
    },
    {
     "expr": "avg(envoy_wasm_remote_load_cache_misses)",
     "legendFormat": "envoy_wasm_remote_load_cache_misses"
    },
    {
     "expr": "avg(envoy_wasm_remote_load_cache_negative_hits)",
     "legendFormat": "envoy_wasm_remote_load_cache_negative_hits"
    }
   ]
  }
 ]
}